//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeHistorian.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkypeHistorian.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chats of {1} exported.
        /// </summary>
        public static string ChatsExported {
            get {
                return ResourceManager.GetString("ChatsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype Historian needs Skype to be started. If Skype is not started then Skype Historian will start it for you..
        /// </summary>
        public static string CheckingForSkypePageNote {
            get {
                return ResourceManager.GetString("CheckingForSkypePageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Skype.
        /// </summary>
        public static string CheckingForSkypePageTitle {
            get {
                return ResourceManager.GetString("CheckingForSkypePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing... {0} of {1}.
        /// </summary>
        public static string ExportingPageClosing {
            get {
                return ResourceManager.GetString("ExportingPageClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype Historian is now exporting your Skype chats....
        /// </summary>
        public static string ExportingPageNote1 {
            get {
                return ResourceManager.GetString("ExportingPageNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, switch to the Skype window and allow Skype Historian to access your chats. Do NOT close Skype during exporting..
        /// </summary>
        public static string ExportingPageNote2 {
            get {
                return ResourceManager.GetString("ExportingPageNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting.
        /// </summary>
        public static string ExportingPageTitle {
            get {
                return ResourceManager.GetString("ExportingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show exported data.
        /// </summary>
        public static string FinishingPageShowExported {
            get {
                return ResourceManager.GetString("FinishingPageShowExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start again.
        /// </summary>
        public static string FinishingPageStartAgain {
            get {
                return ResourceManager.GetString("FinishingPageStartAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing.
        /// </summary>
        public static string FinishingPageTitle {
            get {
                return ResourceManager.GetString("FinishingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exporting is in progress and will be interrupted if you&apos;ll close the window. This will cause the exported data to be corrupted. Close anyway?.
        /// </summary>
        public static string MainWindowConfirmClose {
            get {
                return ResourceManager.GetString("MainWindowConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string MainWindowFinish {
            get {
                return ResourceManager.GetString("MainWindowFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting.
        /// </summary>
        public static string MainWindowLeftBarExporting {
            get {
                return ResourceManager.GetString("MainWindowLeftBarExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing.
        /// </summary>
        public static string MainWindowLeftBarFinishing {
            get {
                return ResourceManager.GetString("MainWindowLeftBarFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        public static string MainWindowLeftBarOptions {
            get {
                return ResourceManager.GetString("MainWindowLeftBarOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Skype.
        /// </summary>
        public static string MainWindowLeftBarSkype {
            get {
                return ResourceManager.GetString("MainWindowLeftBarSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string MainWindowLeftBarWelcome {
            get {
                return ResourceManager.GetString("MainWindowLeftBarWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string MainWindowNext {
            get {
                return ResourceManager.GetString("MainWindowNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version of Skype Historian is released. Would you like to go to the website to download the latest version?.
        /// </summary>
        public static string MainWindowUpdateAvailable {
            get {
                return ResourceManager.GetString("MainWindowUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://eigenein.info/skype-historian/.
        /// </summary>
        public static string MainWindowWebsite {
            get {
                return ResourceManager.GetString("MainWindowWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} messages processed.
        /// </summary>
        public static string MessagesProcessed {
            get {
                return ResourceManager.GetString("MessagesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string OutputTypePageAnd {
            get {
                return ResourceManager.GetString("OutputTypePageAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By members.
        /// </summary>
        public static string OutputTypePageByMembers {
            get {
                return ResourceManager.GetString("OutputTypePageByMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By members, then by month.
        /// </summary>
        public static string OutputTypePageByMembersThenByMonth {
            get {
                return ResourceManager.GetString("OutputTypePageByMembersThenByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By month, then by day, then by members.
        /// </summary>
        public static string OutputTypePageByMonthThenByDayThenByMembers {
            get {
                return ResourceManager.GetString("OutputTypePageByMonthThenByDayThenByMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By month, then by members.
        /// </summary>
        public static string OutputTypePageByMonthThenByMembers {
            get {
                return ResourceManager.GetString("OutputTypePageByMonthThenByMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this if don&apos;t know.
        /// </summary>
        public static string OutputTypePageChooseThis {
            get {
                return ResourceManager.GetString("OutputTypePageChooseThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress exported data.
        /// </summary>
        public static string OutputTypePageCompress {
            get {
                return ResourceManager.GetString("OutputTypePageCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t specified one or both dates within the date filter. Please, specify the date..
        /// </summary>
        public static string OutputTypePageDateFilterError {
            get {
                return ResourceManager.GetString("OutputTypePageDateFilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only messages between.
        /// </summary>
        public static string OutputTypePageDateFilterTitle {
            get {
                return ResourceManager.GetString("OutputTypePageDateFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to export to:.
        /// </summary>
        public static string OutputTypePageFolderBrowserTitle {
            get {
                return ResourceManager.GetString("OutputTypePageFolderBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group all messages.
        /// </summary>
        public static string OutputTypePageGroup {
            get {
                return ResourceManager.GetString("OutputTypePageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to Skype and choose the appropriate output:.
        /// </summary>
        public static string OutputTypePageNote {
            get {
                return ResourceManager.GetString("OutputTypePageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to export to.
        /// </summary>
        public static string OutputTypePageSaveAsTitle {
            get {
                return ResourceManager.GetString("OutputTypePageSaveAsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files.
        /// </summary>
        public static string OutputTypePageTextFiles {
            get {
                return ResourceManager.GetString("OutputTypePageTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to export.
        /// </summary>
        public static string OutputTypePageTitle {
            get {
                return ResourceManager.GetString("OutputTypePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use nicknames in chat titles.
        /// </summary>
        public static string OutputTypePageUseNicknames {
            get {
                return ResourceManager.GetString("OutputTypePageUseNicknames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, your Skype chats were successfully exported! You may close this window..
        /// </summary>
        public static string StatusFinished {
            get {
                return ResourceManager.GetString("StatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype Historian cannot access your chats. Make sure you&apos;re logged in and allowed Skype Historian to access your chats..
        /// </summary>
        public static string StatusSkypeCannotGetChatCollection {
            get {
                return ResourceManager.GetString("StatusSkypeCannotGetChatCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype Historian was unable to initialize Skype. Reinstalling the program may fix the problem..
        /// </summary>
        public static string StatusSkypeInitializationFailed {
            get {
                return ResourceManager.GetString("StatusSkypeInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype Historian was unable to start Skype automatically. Please, try to start Skype manually and run Skype Historian again..
        /// </summary>
        public static string StatusSkypeStartFailed {
            get {
                return ResourceManager.GetString("StatusSkypeStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured. Status Code: {0}. Sorry. Try to run exporting again..
        /// </summary>
        public static string StatusUnknownFailure {
            get {
                return ResourceManager.GetString("StatusUnknownFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting for Skype response....
        /// </summary>
        public static string WaitingForSkypeString {
            get {
                return ResourceManager.GetString("WaitingForSkypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is not designed to collect or transfer your personal data. However, it makes no warranty, thus use this software at your personal risk..
        /// </summary>
        public static string WelcomePageNote {
            get {
                return ResourceManager.GetString("WelcomePageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should have Skype installed..
        /// </summary>
        public static string WelcomePageSkypeInstalled {
            get {
                return ResourceManager.GetString("WelcomePageSkypeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Skype Historian.
        /// </summary>
        public static string WelcomePageTitle {
            get {
                return ResourceManager.GetString("WelcomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program will help you avoid losing your important chats by saving them to different formats. Please, click &quot;Next&quot; to proceed..
        /// </summary>
        public static string WelcomePageWelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomePageWelcomeLabel", resourceCulture);
            }
        }
    }
}
