//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeHistorian.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkypeHistorian.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skype Historian is already running. If you think it&apos;s not so, please, drop a message to skypehistorian@shortmail.com.
        /// </summary>
        public static string AppAlreadyRunning {
            get {
                return ResourceManager.GetString("AppAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} chats of {1} processed.
        /// </summary>
        public static string ChatsExported {
            get {
                return ResourceManager.GetString("ChatsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skype Historian needs Skype to be started. If Skype is not started then Skype Historian will start it for you..
        /// </summary>
        public static string CheckingForSkypePageNote {
            get {
                return ResourceManager.GetString("CheckingForSkypePageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting Skype.
        /// </summary>
        public static string CheckingForSkypePageTitle {
            get {
                return ResourceManager.GetString("CheckingForSkypePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  and others.
        /// </summary>
        public static string ExportingPageAndOthers {
            get {
                return ResourceManager.GetString("ExportingPageAndOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finishing... {0} of {1}.
        /// </summary>
        public static string ExportingPageClosing {
            get {
                return ResourceManager.GetString("ExportingPageClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} messages processed ({1}:{2:D2} left to complete).
        /// </summary>
        public static string ExportingPageMessagesProcessed {
            get {
                return ResourceManager.GetString("ExportingPageMessagesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skype Historian is now exporting your Skype chats....
        /// </summary>
        public static string ExportingPageNote1 {
            get {
                return ResourceManager.GetString("ExportingPageNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, switch to the Skype window and allow Skype Historian to access your chats. Do NOT close Skype during exporting..
        /// </summary>
        public static string ExportingPageNote2 {
            get {
                return ResourceManager.GetString("ExportingPageNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exporting.
        /// </summary>
        public static string ExportingPageTitle {
            get {
                return ResourceManager.GetString("ExportingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sending the feedback....
        /// </summary>
        public static string FinishingPageBusyText {
            get {
                return ResourceManager.GetString("FinishingPageBusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Want to send a feedback?
        ///Write up to 2000 characters and press Finish.
        /// </summary>
        public static string FinishingPageFeedbackWatermark {
            get {
                return ResourceManager.GetString("FinishingPageFeedbackWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show exported data.
        /// </summary>
        public static string FinishingPageShowExported {
            get {
                return ResourceManager.GetString("FinishingPageShowExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show log.
        /// </summary>
        public static string FinishingPageShowLog {
            get {
                return ResourceManager.GetString("FinishingPageShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start again.
        /// </summary>
        public static string FinishingPageStartAgain {
            get {
                return ResourceManager.GetString("FinishingPageStartAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finishing.
        /// </summary>
        public static string FinishingPageTitle {
            get {
                return ResourceManager.GetString("FinishingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The exporting is in progress and will be interrupted if you&apos;ll close the window. This will cause the exported data to be corrupted. Close anyway?.
        /// </summary>
        public static string MainWindowConfirmClose {
            get {
                return ResourceManager.GetString("MainWindowConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish.
        /// </summary>
        public static string MainWindowFinish {
            get {
                return ResourceManager.GetString("MainWindowFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support this program on Flattr!.
        /// </summary>
        public static string MainWindowFlattr {
            get {
                return ResourceManager.GetString("MainWindowFlattr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exporting.
        /// </summary>
        public static string MainWindowLeftBarExporting {
            get {
                return ResourceManager.GetString("MainWindowLeftBarExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finishing.
        /// </summary>
        public static string MainWindowLeftBarFinishing {
            get {
                return ResourceManager.GetString("MainWindowLeftBarFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export Options.
        /// </summary>
        public static string MainWindowLeftBarOptions {
            get {
                return ResourceManager.GetString("MainWindowLeftBarOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting Skype.
        /// </summary>
        public static string MainWindowLeftBarSkype {
            get {
                return ResourceManager.GetString("MainWindowLeftBarSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome.
        /// </summary>
        public static string MainWindowLeftBarWelcome {
            get {
                return ResourceManager.GetString("MainWindowLeftBarWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string MainWindowNext {
            get {
                return ResourceManager.GetString("MainWindowNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The new version of Skype Historian is released. Would you like to go to the website to download the latest version?.
        /// </summary>
        public static string MainWindowUpdateAvailable {
            get {
                return ResourceManager.GetString("MainWindowUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://eigenein.info/skype-historian/.
        /// </summary>
        public static string MainWindowWebsite {
            get {
                return ResourceManager.GetString("MainWindowWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} messages processed.
        /// </summary>
        public static string MessagesProcessed {
            get {
                return ResourceManager.GetString("MessagesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на and.
        /// </summary>
        public static string OutputTypePageAnd {
            get {
                return ResourceManager.GetString("OutputTypePageAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By members.
        /// </summary>
        public static string OutputTypePageByMembers {
            get {
                return ResourceManager.GetString("OutputTypePageByMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By members, then by month.
        /// </summary>
        public static string OutputTypePageByMembersThenByMonth {
            get {
                return ResourceManager.GetString("OutputTypePageByMembersThenByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By month, then by day, then by members.
        /// </summary>
        public static string OutputTypePageByMonthThenByDayThenByMembers {
            get {
                return ResourceManager.GetString("OutputTypePageByMonthThenByDayThenByMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By month, then by members.
        /// </summary>
        public static string OutputTypePageByMonthThenByMembers {
            get {
                return ResourceManager.GetString("OutputTypePageByMonthThenByMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose this if don&apos;t know.
        /// </summary>
        public static string OutputTypePageChooseThis {
            get {
                return ResourceManager.GetString("OutputTypePageChooseThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compress exported data.
        /// </summary>
        public static string OutputTypePageCompress {
            get {
                return ResourceManager.GetString("OutputTypePageCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You haven&apos;t specified one or both dates within the date filter. Please, specify the date..
        /// </summary>
        public static string OutputTypePageDateFilterError {
            get {
                return ResourceManager.GetString("OutputTypePageDateFilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only messages between.
        /// </summary>
        public static string OutputTypePageDateFilterTitle {
            get {
                return ResourceManager.GetString("OutputTypePageDateFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a folder to export to:.
        /// </summary>
        public static string OutputTypePageFolderBrowserTitle {
            get {
                return ResourceManager.GetString("OutputTypePageFolderBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group all messages.
        /// </summary>
        public static string OutputTypePageGroup {
            get {
                return ResourceManager.GetString("OutputTypePageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in to Skype and choose the appropriate output:.
        /// </summary>
        public static string OutputTypePageNote {
            get {
                return ResourceManager.GetString("OutputTypePageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a file to export to.
        /// </summary>
        public static string OutputTypePageSaveAsTitle {
            get {
                return ResourceManager.GetString("OutputTypePageSaveAsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text Files.
        /// </summary>
        public static string OutputTypePageTextFiles {
            get {
                return ResourceManager.GetString("OutputTypePageTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Where to export.
        /// </summary>
        public static string OutputTypePageTitle {
            get {
                return ResourceManager.GetString("OutputTypePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Always use nicknames in chat titles.
        /// </summary>
        public static string OutputTypePageUseNicknames {
            get {
                return ResourceManager.GetString("OutputTypePageUseNicknames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Congratulations, your Skype chats were successfully exported! You may close this window..
        /// </summary>
        public static string StatusFinished {
            get {
                return ResourceManager.GetString("StatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skype Historian cannot access your chats. Make sure you&apos;re logged in and allowed Skype Historian to access your chats..
        /// </summary>
        public static string StatusSkypeCannotGetChatCollection {
            get {
                return ResourceManager.GetString("StatusSkypeCannotGetChatCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skype Historian was unable to initialize Skype. Reinstalling the program may fix the problem..
        /// </summary>
        public static string StatusSkypeInitializationFailed {
            get {
                return ResourceManager.GetString("StatusSkypeInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skype Historian was unable to start Skype automatically. Please, try to start Skype manually and run Skype Historian again..
        /// </summary>
        public static string StatusSkypeStartFailed {
            get {
                return ResourceManager.GetString("StatusSkypeStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An unexpected error has occured. Status Code: {0}. Sorry. Try to run exporting again..
        /// </summary>
        public static string StatusUnknownFailure {
            get {
                return ResourceManager.GetString("StatusUnknownFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Awaiting for Skype response....
        /// </summary>
        public static string WaitingForSkypeString {
            get {
                return ResourceManager.GetString("WaitingForSkypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This software is not designed to collect or transfer your personal data. However, it makes no warranty, thus use this software at your personal risk..
        /// </summary>
        public static string WelcomePageNote {
            get {
                return ResourceManager.GetString("WelcomePageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You should have Skype installed..
        /// </summary>
        public static string WelcomePageSkypeInstalled {
            get {
                return ResourceManager.GetString("WelcomePageSkypeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to Skype Historian.
        /// </summary>
        public static string WelcomePageTitle {
            get {
                return ResourceManager.GetString("WelcomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program will help you avoid losing your important chats by saving them to different formats. Please, click &quot;Next&quot; to proceed..
        /// </summary>
        public static string WelcomePageWelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomePageWelcomeLabel", resourceCulture);
            }
        }
    }
}
